### ISSUE TITLE
How to generate "center_*_*.txt“ file？

### ISSUE THREAD

**Issue by LYKlyk** [RonLek/FastV2C-HandNet#2]
I have a question about whether you should generate center_*_*.txt in advance? How to generate it ? Thank you.

**Comment by RonLek** [comment]
Hi @LYKlyk . Yes, the center_.txt files need to be generated in advance. They provide reference centers and offsets so that the image is cropped properly. The precomputed centers are obtained by training the hand center estimation network from [DeepPrior++](https://arxiv.org/pdf/1708.08325.pdf) .
