### ISSUE TITLE
I try to run "hand render" code, but it cannot get expected result.

### ISSUE THREAD

**Issue by LYKlyk** [RonLek/FastV2C-HandNet#5]
I try to run "hand render" code, but it cannot get expected result.

**Comment by RonLek** [comment]
A common mistake could be improper paths for the `database_dir` and `center_dir` variables in the hand_image_renderer.py file. You might want to do an `os.path.exists()` and check if the paths exists on your system. The paths given in the file are paths to the database and centers on my system. You need to change it correspondingly for yours.

**Comment by LYKlyk** [comment]
Thank you very much.
