### ISSUE TITLE
Have you managed to improve the accuracy?

### ISSUE THREAD

**Issue by happyCodingSusan** [RonLek/FastV2C-HandNet#6]
@RonLek , nice work! Thanks for sharing!
Wonder if you have managed to improve the accuracy while maintaining the similar speed.

**Comment by RonLek** [comment]
@happyCodingSusan the model does take a slight hit on the accuracy in getting the speed up. It is more suited for small-sized applications that require high speed results with short model sizes and are not looking for an exacting accuracy. You can read more about it in the **Conclusion** part of the [paper](https://arxiv.org/pdf/1907.06327).
